#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnome-todo
Version  : 3.28.1
Release  : 18
URL      : https://download.gnome.org/sources/gnome-todo/3.28/gnome-todo-3.28.1.tar.xz
Source0  : https://download.gnome.org/sources/gnome-todo/3.28/gnome-todo-3.28.1.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: gnome-todo-bin = %{version}-%{release}
Requires: gnome-todo-data = %{version}-%{release}
Requires: gnome-todo-license = %{version}-%{release}
Requires: gnome-todo-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : glibc-bin
BuildRequires : gnome-online-accounts-dev
BuildRequires : json-glib-dev
BuildRequires : libpeas-dev
BuildRequires : pkgconfig(goa-1.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(libecal-2.0)
BuildRequires : pkgconfig(libpeas-1.0)
BuildRequires : pkgconfig(rest-0.7)
BuildRequires : rest-dev
Patch1: 0001-eds-Port-to-libecal-2.0.patch

%description
# GNOME To Do
GNOME To Do is a simple, intuitive and yet powerfull application to manage your
personal tasks. It uses GNOME technologies and has complete integration with the
GNOME desktop environment.

%package bin
Summary: bin components for the gnome-todo package.
Group: Binaries
Requires: gnome-todo-data = %{version}-%{release}
Requires: gnome-todo-license = %{version}-%{release}

%description bin
bin components for the gnome-todo package.


%package data
Summary: data components for the gnome-todo package.
Group: Data

%description data
data components for the gnome-todo package.


%package dev
Summary: dev components for the gnome-todo package.
Group: Development
Requires: gnome-todo-bin = %{version}-%{release}
Requires: gnome-todo-data = %{version}-%{release}
Provides: gnome-todo-devel = %{version}-%{release}
Requires: gnome-todo = %{version}-%{release}

%description dev
dev components for the gnome-todo package.


%package license
Summary: license components for the gnome-todo package.
Group: Default

%description license
license components for the gnome-todo package.


%package locales
Summary: locales components for the gnome-todo package.
Group: Default

%description locales
locales components for the gnome-todo package.


%prep
%setup -q -n gnome-todo-3.28.1
cd %{_builddir}/gnome-todo-3.28.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1586231708
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gnome-todo
cp %{_builddir}/gnome-todo-3.28.1/COPYING %{buildroot}/usr/share/package-licenses/gnome-todo/338650eb7a42dd9bc1f1c6961420f2633b24932d
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gnome-todo

%files
%defattr(-,root,root,-)
/usr/lib64/gnome-todo/plugins/score/score.plugin
/usr/lib64/gnome-todo/plugins/score/score/__init__.py
/usr/lib64/gnome-todo/plugins/unscheduled-panel/unscheduled-panel.plugin
/usr/lib64/gnome-todo/plugins/unscheduled-panel/unscheduled-panel/__init__.py

%files bin
%defattr(-,root,root,-)
/usr/bin/gnome-todo

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Gtd-1.0.typelib
/usr/share/applications/org.gnome.Todo.desktop
/usr/share/dbus-1/services/org.gnome.Todo.service
/usr/share/gir-1.0/*.gir
/usr/share/glib-2.0/schemas/org.gnome.todo.background.gschema.xml
/usr/share/glib-2.0/schemas/org.gnome.todo.enums.xml
/usr/share/glib-2.0/schemas/org.gnome.todo.gschema.xml
/usr/share/glib-2.0/schemas/org.gnome.todo.txt.gschema.xml
/usr/share/gnome-todo/org.gnome.Todo.Autostart.desktop
/usr/share/icons/hicolor/16x16/apps/org.gnome.Todo.png
/usr/share/icons/hicolor/22x22/apps/org.gnome.Todo.png
/usr/share/icons/hicolor/256x256/apps/org.gnome.Todo.png
/usr/share/icons/hicolor/32x32/apps/org.gnome.Todo.png
/usr/share/icons/hicolor/48x48/apps/org.gnome.Todo.png
/usr/share/icons/hicolor/512x512/apps/org.gnome.Todo.png
/usr/share/icons/hicolor/symbolic/apps/org.gnome.Todo-symbolic.svg
/usr/share/metainfo/org.gnome.Todo.appdata.xml

%files dev
%defattr(-,root,root,-)
/usr/include/gnome-todo/gnome-todo.h
/usr/include/gnome-todo/gtd-activatable.h
/usr/include/gnome-todo/gtd-enums.h
/usr/include/gnome-todo/gtd-manager.h
/usr/include/gnome-todo/gtd-notification.h
/usr/include/gnome-todo/gtd-object.h
/usr/include/gnome-todo/gtd-panel.h
/usr/include/gnome-todo/gtd-provider.h
/usr/include/gnome-todo/gtd-task-list-view.h
/usr/include/gnome-todo/gtd-task-list.h
/usr/include/gnome-todo/gtd-task.h
/usr/include/gnome-todo/gtd-timer.h
/usr/include/gnome-todo/gtd-types.h
/usr/include/gnome-todo/gtd-utils.h
/usr/include/gnome-todo/gtd-window.h
/usr/lib64/pkgconfig/gnome-todo.pc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gnome-todo/338650eb7a42dd9bc1f1c6961420f2633b24932d

%files locales -f gnome-todo.lang
%defattr(-,root,root,-)

