#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnome-todo
Version  : 3.28.1
Release  : 11
URL      : https://download.gnome.org/sources/gnome-todo/3.28/gnome-todo-3.28.1.tar.xz
Source0  : https://download.gnome.org/sources/gnome-todo/3.28/gnome-todo-3.28.1.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: gnome-todo-bin
Requires: gnome-todo-data
Requires: gnome-todo-license
Requires: gnome-todo-locales
BuildRequires : buildreq-meson
BuildRequires : glibc-bin
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(goa-1.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(libecal-1.2)
BuildRequires : pkgconfig(libpeas-1.0)
BuildRequires : pkgconfig(rest-0.7)

%description
# GNOME To Do
GNOME To Do is a simple, intuitive and yet powerfull application to manage your
personal tasks. It uses GNOME technologies and has complete integration with the
GNOME desktop environment.

%package bin
Summary: bin components for the gnome-todo package.
Group: Binaries
Requires: gnome-todo-data
Requires: gnome-todo-license

%description bin
bin components for the gnome-todo package.


%package data
Summary: data components for the gnome-todo package.
Group: Data

%description data
data components for the gnome-todo package.


%package dev
Summary: dev components for the gnome-todo package.
Group: Development
Requires: gnome-todo-bin
Requires: gnome-todo-data
Provides: gnome-todo-devel

%description dev
dev components for the gnome-todo package.


%package license
Summary: license components for the gnome-todo package.
Group: Default

%description license
license components for the gnome-todo package.


%package locales
Summary: locales components for the gnome-todo package.
Group: Default

%description locales
locales components for the gnome-todo package.


%prep
%setup -q -n gnome-todo-3.28.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535062852
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/doc/gnome-todo
cp COPYING %{buildroot}/usr/share/doc/gnome-todo/COPYING
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gnome-todo

%files
%defattr(-,root,root,-)
/usr/lib64/gnome-todo/plugins/score/score.plugin
/usr/lib64/gnome-todo/plugins/score/score/__init__.py
/usr/lib64/gnome-todo/plugins/unscheduled-panel/unscheduled-panel.plugin
/usr/lib64/gnome-todo/plugins/unscheduled-panel/unscheduled-panel/__init__.py

%files bin
%defattr(-,root,root,-)
/usr/bin/gnome-todo

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Gtd-1.0.typelib
/usr/share/applications/org.gnome.Todo.desktop
/usr/share/dbus-1/services/org.gnome.Todo.service
/usr/share/gir-1.0/*.gir
/usr/share/glib-2.0/schemas/org.gnome.todo.background.gschema.xml
/usr/share/glib-2.0/schemas/org.gnome.todo.enums.xml
/usr/share/glib-2.0/schemas/org.gnome.todo.gschema.xml
/usr/share/glib-2.0/schemas/org.gnome.todo.txt.gschema.xml
/usr/share/gnome-todo/org.gnome.Todo.Autostart.desktop
/usr/share/icons/hicolor/16x16/apps/org.gnome.Todo.png
/usr/share/icons/hicolor/22x22/apps/org.gnome.Todo.png
/usr/share/icons/hicolor/256x256/apps/org.gnome.Todo.png
/usr/share/icons/hicolor/32x32/apps/org.gnome.Todo.png
/usr/share/icons/hicolor/48x48/apps/org.gnome.Todo.png
/usr/share/icons/hicolor/512x512/apps/org.gnome.Todo.png
/usr/share/icons/hicolor/symbolic/apps/org.gnome.Todo-symbolic.svg
/usr/share/metainfo/org.gnome.Todo.appdata.xml

%files dev
%defattr(-,root,root,-)
/usr/include/gnome-todo/gnome-todo.h
/usr/include/gnome-todo/gtd-activatable.h
/usr/include/gnome-todo/gtd-enums.h
/usr/include/gnome-todo/gtd-manager.h
/usr/include/gnome-todo/gtd-notification.h
/usr/include/gnome-todo/gtd-object.h
/usr/include/gnome-todo/gtd-panel.h
/usr/include/gnome-todo/gtd-provider.h
/usr/include/gnome-todo/gtd-task-list-view.h
/usr/include/gnome-todo/gtd-task-list.h
/usr/include/gnome-todo/gtd-task.h
/usr/include/gnome-todo/gtd-timer.h
/usr/include/gnome-todo/gtd-types.h
/usr/include/gnome-todo/gtd-utils.h
/usr/include/gnome-todo/gtd-window.h
/usr/lib64/pkgconfig/gnome-todo.pc

%files license
%defattr(-,root,root,-)
/usr/share/doc/gnome-todo/COPYING

%files locales -f gnome-todo.lang
%defattr(-,root,root,-)

